[tools]
go = "latest"
rust = "latest"
nodejs = "latest"
python = "latest"
chezmoi = "latest"
consul = "latest"
packer = "latest"
serf = "latest"
shellcheck = "latest"
shfmt = "latest"
terraform = "latest"
terraform-ls = "latest"
vault = "latest"
zig = "latest"
"cargo:atuin" = "latest"
"cargo:zellij" = "latest"
"cargo:stylua" = "latest"
"cargo:rbw" = "latest"
"cargo:shellharden" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/cmd/callgraph" = "latest"
"go:golang.org/x/tools/cmd/deadcode" = "latest"
"go:braces.dev/errtrace/cmd/errtrace" = "latest"
"go:golang.org/x/mobile/cmd/gobind" = "latest"
"go:github.com/ofabry/go-callvis" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:github.com/incu6us/goimports-reviser/v3" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:github.com/magefile/mage" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:github.com/golang/protobuf/protoc-gen-go" = "latest"
"go:github.com/boyter/scc/v3" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
pipx = "latest"

[settings]
experimental = true
