[[language]]
name = "go"
auto-format = true
formatter = { command = "go_format.sh" }
language-servers = [  { name = "gopls", except-features = ["workspace-command"]}, "execlsp-go" ]

[[language]]
name = "html"
auto-format = true
language-servers = [ "html-languageserver" ]

[[language]]
name = "css"
auto-format = true
language-servers = [ "css-languageserver" ]

[[language]]
name = "scss"
auto-format = true
language-servers = [ "css-languageserver" ]

[[language]]
name = 'javascript'
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = 'typescript'
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = 'jsx'
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = 'tsx'
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = 'svelte'
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = 'c'
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = "markdown"
language-servers = [ {name="zk", except-features=["workspace-command"]}, "marksman", "execlsp-zk" ]
indent = { tab-width = 2, unit = " " }

[language-server.zk]
command = "zk"
args = ["lsp"]

[language-server.marksman]
command = "marksman"

[language-server.execlsp-go]
command = "execlsp"
args = ["-presets", "go"]

[language-server.execlsp-zk]
command = "execlsp"
args = ["-presets", "zk"]

[language-server.gopls.config]
"formatting.gofumpt" = true

