[colors]
color_term = "ansi"
overdue = "bright red"
threshold = "red"
top = "bright red"
important = "white"
done = "bright black"
today = "bright yellow"
soon = "white"
old = "bright black"

[ranges]
soon = 3
important = "b"

[global]
filename = "{{ env "HOME" }}/Dropbox/todo.txt"
creation_date_auto = true
fields = "done,pri,thr,due,rec,tags"
sort = 'thr,pri'
first_sunday = false
strict_mode = false
clean_subject = "all"
