[notebook]
dir = "~/notes"

[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

[extra]

[group.daily]
paths = ["journal/daily"]

[group.daily.note]
filename = "{{ format-date now '%Y-%m-%d' }}"
template = "daily.md"

[group.weekly]
paths = ["journal/weekly"]
[group.weekly.note]
filename = "{{ format-date now '%Y-W%U' }}"
template = "weekly.md"

[group.projects]
paths = ["projects/personal", "projects/work"]

[group.projects.tool]
fzf-line = '[{{metadata.state}}] {{style "bold" title}}'

[format.markdown]
link-format = "[[{{path}}|{{title}}]]"
hashtags = true

[tool]
editor = "hx"
fzf-preview = "bat -p --color always {-1}"


[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[lsp.completion]

[filter]

[alias]
n = 'zk new --title=(string join " " $argv)'
nwproject = 'zk new --template=wproject.md --title=(string join " " $argv) projects/work'
npproject = 'zk new --template=pproject.md --title=(string join " " $argv) projects/personal'
e = 'zk edit --interactive'
d = 'zk new --no-input journal/daily'
w = 'zk new --no-input journal/weekly'
last = 'zk edit --limit 1 --sort modified- (string join " " $argv)'
conf = '$EDITOR ~/.config/zk/config.toml'
sync = 'git-sync -ns'
rm = 'rm $argv.md || rm $argv'
wprojects = 'zk edit --tag project --tag work --interactive projects/work'
pprojects = 'zk edit --tag project --tag personal --interactive projects/personal'
